language: rust
sudo: false
rust:
  - 1.16.0
  - stable
  - beta
  - nightly
matrix:
  include:
    - rust: 1.31.0
      script:
        - cargo test --verbose --features kv_unstable
        - cargo test --verbose --features "kv_unstable std"
    - rust: stable
      script:
        - rustup target add thumbv6m-none-eabi
        - cargo build --verbose --target=thumbv6m-none-eabi
script:
  - cargo build --verbose
  - cargo build --verbose --features serde
  - cargo build --verbose --features std
  - cargo test --verbose
  - cargo test --verbose --features serde
  - cargo test --verbose --features std
  - cargo run --verbose --manifest-path test_max_level_features/Cargo.toml
  - cargo run --verbose --manifest-path test_max_level_features/Cargo.toml --release

notifications:
  email:
    on_success: never
